dependencies:
  pkgs:
    - qtile
    - qtile-extras
    - btop
    - kitty
    - eww-git
    - picom-ftlabs-git
    - rofi
    - dunst
    - nerd-fonts
    - pamixer
    - arandr
    - pavucontrol
    - network-manager-applet
    - blueman
    - brightnessctl
    - xrandr
    - neofetch
    - python-pip
    - gdm-prime
    - python-dbus-next
    - fontawesome
    - nautilus
    - xf86-video-intel
  commands:
    - sudo systemctl start bluetooth.service
    - sudo systemctl enable bluetooth.service
    - pip install fontawesome --break-system-packages
    - cp -r ./config/qtile ~/.config/qtile
    - cp -r ./config/rofi ~/.config/rofi
    - cp -r ./config/eww ~/.config/eww
    - cp -r ./config/btop ~/.config/btop
    - cp -r ./config/picom ~/.config/picom
    - cp -r ./config/dunst ~/.config/dunst
    - cp -r ./config/kitty ~/.config/kitty
    - cp -r ./config/neofetch ~/.config/neofetch
terminal:
  pkgs:
    - zsh
    - neovim
    - lazygit
    - ranger
    - jq
    - fzf
  commands:
    - sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    - git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
    - git clone https://github.com/joshskidmore/zsh-fzf-history-search ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-fzf-history-search
    - git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
    - git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
    - sudo chsh -s $(which zsh)
    - cp ./.zshrc ~/.zshrc
nvidia:
  pkgs:
    - optimus-manager-qt
    - nvidia-inst
  commands:
    - sudo systemctl enable optimus-manager
    - nvidia-inst
dependencies-extras:
  pkgs:
    - lazynvim
    - starship
    - google-chrome
    - nitrogen
    - visual-studio-code-bin
    - spotify
    - discord
    - doko
    - k9s
    - obsidian
    - postman
    - kind
    - rclone
  commands:
    - sudo rm /usr/share/endeavouros/splash.png
    - sudo mv ~/.config/qtile/splash.png /usr/share/endeavouros/
    - cp -r ./nvim/lua ~/.config/nvim/lua
