#!/bin/bash

# autorandr --change &
picom &
dunst & 
nitrogen --restore & 
eww daemon --config "$HOME/.config/eww/menu" &
nm-applet &
blueman-applet & 
optimus-manager-qt &
rclone mount google: ~/Documents/drive/ &
exit