#!/bin/bash

if [ "$1" == "monitor" ]; then
    brightnessctl i | grep -oP '\(\K[^%\)]+'
elif [ "$1" == "kbd" ]; then
    brightnessctl --device='asus::kbd_backlight' g
else
    echo "Invalid input. Please provide 'monitor' or 'kbd'."
    exit 1
fi