#!/bin/bash

sth="nmcli -t -f SIGNAL,ACTIVE device wifi list | awk -F: '$2=="yes" {print $1}'"

symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo "󰖪 " && exit

if [ "$sth" -gt "20" ]; then
	notify-send -u critical "Low network connection"
fi
echo " " 
}

name() {
device_info=$(nmcli -t -f GENERAL.STATE,GENERAL.CONNECTION device show wlan0)

if echo "$device_info" | grep -q "GENERAL.STATE:100 (connected)"; then
	wifi_name=$(echo "$device_info" | grep "GENERAL.CONNECTION" | cut -d ':' -f2)
    echo "$wifi_name"
else
    echo "Not connected"
fi
}

[ "$1" = "run" ] && nm-connection-editor
[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit