#!/bin/bash

repo() {
  updates=$(yay -Qu --repo | wc -l)
  [ -z "$updates" ] && updates=0
  echo "$updates"
}

aur() {
  updates=$(yay -Qu --aur | wc -l)
  [ -z "$updates" ] && updates=0
  echo "$updates"
}

sum() {
  repo_updates=$(repo)
  aur_updates=$(aur)
  total_updates=$((repo_updates + aur_updates))
  echo "$total_updates"
}

updates() {
  if [ "$(sum)" -gt 0 ]; then
    echo " "
  else
    echo " "
  fi
}

[ "$1" = "icon" ] && updates && exit
[ "$1" = "aur" ] && aur && exit
[ "$1" = "repo" ] && repo && exit
[ "$1" = "sum" ] && sum && exit
[ "$1" = "aurrun" ] && kitty --title kitty_floats yay -Su --aur && exit
[ "$1" = "reporun" ] && kitty --title kitty_floats yay -Su --repo && exit
[ "$1" = "sumrun" ] && kitty --title kitty_floats yay -Su  && exit