#!/bin/bash

uptime_output=$(uptime)
uptime=$(echo "$uptime_output" | awk '{print $3}' | sed 's/,//')

hours=$(echo "$uptime" | cut -d ':' -f 1)
minutes=$(echo "$uptime" | cut -d ':' -f 2 | sed 's/^0//')  

if [ "$hours" -eq 1 ]; then
    hours_string="hour"
else
    hours_string="hours"
fi

if [ "$minutes" -eq 1 ]; then
    minutes_string="minute"
else
    minutes_string="minutes"
fi

echo "Up $hours $hours_string, $minutes $minutes_string"
