#!/bin/bash
battery_info=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)
battery_level=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "percentage" | awk '{print $2}' | cut -d "%" -f1)
charging_status=$(echo "$battery_info" | grep "state" | awk '{print $2}')

level(){
    echo $battery_level
}
symbol(){

if [ "$charging_status" == "charging" ]; then
    echo "󰂄" && exit
fi

if [ "$battery_level" -ge 0 ] && [ "$battery_level" -le 10 ]; then
    echo "󰁺"  
elif [ "$battery_level" -ge 11 ] && [ "$battery_level" -le 20 ]; then
    echo "󰁺"  
elif [ "$battery_level" -ge 21 ] && [ "$battery_level" -le 30 ]; then
    echo "󰁼"  
elif [ "$battery_level" -ge 31 ] && [ "$battery_level" -le 40 ]; then
    echo "󰁽"      
elif [ "$battery_level" -ge 41 ] && [ "$battery_level" -le 50 ]; then
    echo "󰁾"     
elif [ "$battery_level" -ge 51 ] && [ "$battery_level" -le 60 ]; then
    echo "󰁿"     
elif [ "$battery_level" -ge 61 ] && [ "$battery_level" -le 70 ]; then
    echo "󰂀"     
elif [ "$battery_level" -ge 71 ] && [ "$battery_level" -le 80 ]; then
    echo "󰂁"
elif [ "$battery_level" -ge 81 ] && [ "$battery_level" -le 90 ]; then
    echo "󰂂" 
else
    echo "󰁹"  
fi
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "level" ] && level && exit
[ "$1" = "run" ] && kitty --title kitty_floats btop && exit