#!/bin/bash

case "$1" in
    "logout")
        echo "Logging out..."
        pkill -KILL -u "$(whoami)"
        ;;
    "reboot")
        echo "Restarting..."
        systemctl reboot
        ;;
    "power")
        echo "Shutting down..."
        systemctl poweroff
        ;;
    *)
        echo "Niedostępna operacja. Dostępne opcje: logout, restart, poweroff."
        ;;
esac